name: PopulationDensity
main: me.ryanhamshire.PopulationDensity.PopulationDensity
softdepend: [Multiverse-Core, My Worlds, Transporter, MystCraft]
version: 5.8
commands:
   visit:
      description: Teleports the player to a specified region.
      usage: /visit <online player name> OR /visit <region name>
      aliases: [visitregion, vr, visitpost]
   homeregion:
      description: Returns the player to his/her home region.
      usage: /HomeRegion
      aliases: [gohome, homepost]
   sethomeregion:
      description: Updates a user's home region to his current region.
      usage: /SetHomeRegion
      aliases: [movein, sethomeregion, sethomepost]
   nameregion:
      description: Names a wilderness region.
      usage: /nameregion <name>
      permission: populationdensity.nameregion
   renameregion:
      description: Renames a region.
      usage: /renameregion <name>
      permission: populationdensity.renameregion
   whichregion:
      description: Tells the player which region he's in.
      usage: /WhichRegion
   newestregion:
      description: Teleports the player to the newest region.
      usage: /newestregion
   cityregion:
      description: Teleports the player to the server spawn.
      usage: /cityregion
      aliases: [spawn, spawnregion]
   addregion:
      description: Closes the current open region and opens a new one.
      usage: /addregion
      permission: populationdensity.addregion
   randomregion:
      description: Teleports you to a random region.
      usage: /randomregion 
   scanregion:
      description: Scans the region you're standing in for resources.
      usage: /ScanRegion
      permission: populationdensity.addregion
   addregionpost:
      description: Generates a region post at the center of the current region.
      usage: /AddRegionPost
      permission: populationdensity.addregion
   invite:
      description: Invites a player to visit your home region.
      usage: /invite <player name>
      alises: [invitetoregion, regioninvite, inviteregion]
   loginpriority:
      description: Sets the login priority for a player.
      usage: /LoginPriority <player name> <priority, 0 - 100>
      permission: populationdensity.setloginpriority
   randomregion:
      description: Teleports the player to a random region.
      usage: /randomregion
   thinentities:
      description: Forces entity thinning to run immediately.
      usage: /thinentities
      permission: populationdensity.forcethinning
   simlag:
      description: Simulates lag.  Intended for testing - do not use!
      usage: /simlag <ticksPerSecond>
      permission: populationdensity.simulatelag
   lag:
      description: Checks for server CPU lag.
      usage: /lag
   listregions:
      description: Lists all available regions.
      usage: /listregions
      aliases: [regions, regionlist, regionslist, allregions]
      permission: populationdensity.listregions
   sendregion:
      description: Sends a player to his home region or to a specificied region.
      usage: /SendRegion <player> <region> (if no region specified, player goes home)
      aliases: [sendtoregion]
      permission: populationdensity.sendregion
permissions:
    populationdensity.*:
        description: Grants all administrative privileges.
        children:
            populationdensity.buildbreakanywhere: true
            populationdensity.teleportanywhere: true
            populationdensity.addregion: true
            populationdensity.idle: true
            populationdensity.adminlogin: true
            populationdensity.setloginpriority: true
            populationdensity.forcethinning: true
            populationdensity.sendregion: true
            populationdensity.nameregion: true
            populationdensity.renameregion: true
            populationdensity.unlimitedhoppers: true
    populationdensity.newestregion:
        description: Grants permission to use /NewestRegion.
        default: op
    populationdensity.buildbreakanywhere:
        description: Grants permission to edit anywhere in the managed world, including region posts.
        default: op
    populationdensity.teleportanywhere:
        description: Grants permission to use region-based teleportation from any location.
        default: op
    populationdensity.addregion:
        description: Grants permission to the /addregion command.
        default: op    
    populationdensity.idle:
        description: Grants a player permission to idle (without being kicked).
        default: op
    populationdensity.adminlogin:
        description: Grants a player permission to fill a player slot reserved for administrators.
        default: op
    populationdensity.prioritylogin:
        description: Raises a player's login priority level to 25 of 100.
        default: false
    populationdensity.elitelogin:
        description: Raises a player's login priority level to 50 of 100.
        default: false
    populationdensity.setloginpriority:
        description: Grants a player permission to use /SetLoginPriority.
        default: op
    populationdensity.forcethinning:
        description: Grants a player permission to use /ThinEntities.
        default: op
    populationdensity.sendregion:
        description: Grants a player permission to use /SendRegion.
        default: op
    populationdensity.nameregion:
        description: Grants a player permission to use /NameRegion.
        default: op
    populationdensity.renameregion:
        description: Grants a player permission to use /RenameRegion.
        default: op
    populationdensity.simulatelag:
        description: Grants a player permission to use /SimLag.
        default: op
    populationdensity.listregions:
        description: Grants access to /ListRegions.
        default: true
    populationdensity.unlimitedhoppers:
        description: Players with this permission node ignore the hoppers-per-chunk limit defined in the config file.
        default: op